// >>> LOGIN
export const LOGGING_IN_START = "LOGGING_IN_START";
export const LOGGING_IN_SUCCESS = "LOGGING_IN_SUCCESS";
export const LOGGING_IN_FAILURE = "LOGGING_IN_FAILURE";
export const LOGGING_IN_FAILURE_INVALID_EMAIL = "LOGGING_IN_FAILURE_INVALID_EMAIL";
export const LOGGING_IN_FAILURE_INVALID_PASSWORD = "LOGGING_IN_FAILURE_INVALID_PASSWORD";
export const LOGGING_IN_FAILURE_INVALID_PASSWORD_LENGTH = "LOGGING_IN_FAILURE_INVALID_PASSWORD_LENGTH";

// >>> REGISTERING
export const REGISTERING_START = "REGISTERING_START"
export const REGISTERING_SUCCESS = "REGISTERING_SUCCESS"
export const REGISTERING_FAILURE = "REGISTERING_FAILURE"
export const REGISTERING_FAILURE_NO_ACCOUNT_TYPE = "REGISTERING_FAILURE_NO_ACCOUNT_TYPE"
export const REGISTERING_FAILURE_DUPLICATE_EMAIL = "REGISTERING_FAILURE_DUPLICATE_EMAIL";
export const REGISTERING_FAILURE_PASSWORD_INVALID_CHARACTERS = "REGISTERING_FAILURE_PASSWORD_INVALID_CHARACTERS";
export const REGISTERING_FAILURE_PASSWORDS_DONT_MATCH = "REGISTERING_FAILURE_PASSWORDS_DONT_MATCH";

// >>> USER
export const GETTING_USER_START = "GETTING_USER_START";
export const GETTING_USER_SUCCESS = "GETTING_USER_SUCCESS";
export const GETTING_USER_FAILURE = "GETTING_USER_FAILURE";
export const CLEAR_USER_FROM_STORE = "CLEAR_USER_FROM_STORE"

export const PATCHING_USER_INFO_START = "PATCHING_USER_INFO_START";
export const PATCHING_USER_INFO_SUCCESS = "PATCHING_USER_INFO_SUCCESS";
export const PATCHING_USER_INFO_FAILURE = "PATCHING_USER_INFO_FAILURE";

export const CHANGING_PASSWORD_START = "CHANGING_PASSWORD_START";
export const CHANGING_PASSWORD_SUCCESS = "CHANGING_PASSWORD_SUCCESS";
export const CHANGING_PASSWORD_FAILURE = "CHANGING_PASSWORD_FAILURE";

export const DELETING_USER_START = "DELETING_USER_START";
export const DELETING_USER_SUCCESS = "DELETING_USER_SUCCESS";
export const DELETING_USER_FAILURE = "DELETING_USER_FAILURE";

// >>> BALANCE
export const GETTING_BALANCE_START = "GETTING_BALANCE_START";
export const GETTING_BALANCE_SUCCESS = "GETTING_BALANCE_SUCCESS";
export const GETTING_BALANCE_FAILURE = "GETTING_BALANCE_FAILURE";
export const CLEAR_BALANCE_FROM_STORE = "CLEAR_BALANCE_FROM_STORE";

// >>> SELECTING TIP
export const SET_SELECTED_TIP_AMOUNT = "SET_SELECTED_TIP_AMOUNT";
export const CLEAR_SELECTED_TIP_AMOUNT_FROM_STORE = "CLEAR_SELECTED_TIP_AMOUNT_FROM_STORE";

export const SET_SELECTED_TIP_RECEIVER_CODE = "SET_SELECTED_TIP_RECEIVER_CODE";
export const CLEAR_SELECTED_TIP_RECEIVER_CODE_FROM_STORE = "CLEAR_SELECTED_TIP_RECEIVER_CODE_FROM_STORE";
export const SET_SELECTED_TIP_RECEIVER = "SET_SELECTED_TIP_RECEIVER";
export const CLEAR_SELECTED_TIP_RECEIVER_FROM_STORE = "CLEAR_SELECTED_TIP_RECEIVER_FROM_STORE";

export const SET_SELECTED_PAYMENT_METHOD_TYPE = "SET_SELECTED_PAYMENT_METHOD_TYPE";
export const CLEAR_SELECTED_PAYMENT_METHOD_TYPE_FROM_STORE = "CLEAR_SELECTED_PAYMENT_METHOD_TYPE_FROM_STORE";
export const SET_SELECTED_PAYMENT_METHOD = "SET_SELECTED_PAYMENT_METHOD";
export const CLEAR_SELECTED_PAYMENT_METHOD_FROM_STORE = "CLEAR_SELECTED_PAYMENT_METHOD_FROM_STORE";

export const CLEAR_ENTIRE_TIP_STORE = "CLEAR_ENTIRE_TIP_STORE";

// >>> TIP RECEIVER
// Search takes place when entering it in the code-input, followed by selection and eventual deselection
export const SEARCHING_TIP_RECEIVER_START = "SEARCHING_TIP_RECEIVER_START";
export const SEARCHING_TIP_RECEIVER_FAILURE = "SEARCHING_TIP_RECEIVER_FAILURE"
export const SEARCHING_TIP_RECEIVER_SUCCESS = "SEARCHING_TIP_RECEIVER_SUCCESS"

// >>> TRANSACTIONS
export const SENDING_TRANSACTION_START = "SENDING_TRANSACTION_START";
export const SENDING_TRANSACTION_SUCCESS = "SENDING_TRANSACTION_SUCCESS";
export const SENDING_TRANSACTION_FAILURE = "SENDING_TRANSACTION_FAILURE";
export const CLEAR_CURRENT_TRANSACTION_FROM_STORE = "CLEAR_CURRENT_TRANSACTION_FROM_STORE";

export const FETCHING_TRANSACTIONS_START = "FETCHING_TRANSACTIONS_START";
export const FETCHING_TRANSACTIONS_SUCCESS = "FETCHING_TRANSACTIONS_SUCCESS";
export const FETCHING_TRANSACTIONS_FAILURE = "FETCHING_TRANSACTIONS_FAILURE";
export const CLEAR_TRANSACTIONS_LIST_FROM_STORE = "CLEAR_TRANSACTIONS_LIST_FROM_STORE";

// >>> DEPOSITING
export const SET_DEPOSIT_AMOUNT = "SET_DEPOSIT_AMOUNT";
export const CLEAR_DEPOSIT_FROM_STORE = "CLEAR_DEPOSIT_FROM_STORE";

export const DEPOSITING_START = "DEPOSITING_START";
export const DEPOSITING_SUCCESS = "DEPOSITING_SUCCESS";
export const DEPOSITING_FAILURE = "DEPOSITING_FAILURE";

// >>> WITHDRAWING
export const SET_WITHDRAWAL_AMOUNT = "SET_WITHDRAWAL_AMOUNT"
export const CLEAR_WITHDRAWAL_FROM_STORE = "CLEAR_WITHDRAWAL_FROM_STORE";

export const WITHDRAWING_START = "WITHDRAWING_START";
export const WITHDRAWING_SUCCESS = "WITHDRAWING_SUCCESS";
export const WITHDRAWING_FAILURE = "WITHDRAWING_FAILURE";

// >>> PAYMENT METHODS
export const FETCHING_PAYMENT_METHODS_START = "FETCHING_PAYMENT_METHODS_START";
export const FETCHING_PAYMENT_METHODS_SUCCESS = "FETCHING_PAYMENT_METHODS_SUCCESS";
export const FETCHING_PAYMENT_METHODS_FAILURE = "FETCHING_PAYMENT_METHODS_FAILURE";
export const CLEAR_PAYMENT_METHODS_FROM_STORE = "CLEAR_PAYMENT_METHODS_FROM_STORE";

export const ADDING_PAYMENT_METHOD_START = "ADDING_PAYMENT_METHOD_START";
export const ADDING_PAYMENT_METHOD_SUCCESS = "ADDING_PAYMENT_METHOD_SUCCESS";
export const ADDING_PAYMENT_METHOD_FAILURE = "ADDING_PAYMENT_METHOD_FAILURE";

export const REMOVING_PAYMENT_METHOD_START = "REMOVING_PAYMENT_METHOD_START";
export const REMOVING_PAYMENT_METHOD_SUCCESS = "REMOVING_PAYMENT_METHOD_SUCCESS";
export const REMOVING_PAYMENT_METHOD_FAILURE = "REMOVING_PAYMENT_METHOD_FAILURE";

// >>> CLEAR ENTIRE STORE
export const CAUTION_CLEAR_ENTIRE_STORE = "CAUTION_CLEAR_ENTIRE_STORE"