// LOGIN
export const LOGIN_START = "LOGIN_START";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";
// >>> Add specific error messages for invalid email, invalid password, etc.

// REGISTRATION
export const REGISTRATION_START = "REGISTRATION_START"
export const REGISTRATION_SUCCESS = "REGISTRATION_SUCCESS"
export const REGISTRATION_FAILURE = "REGISTRATION_FAILURE"
// export const REGISTRATION_FAILURE_EMAIL_TAKEN = "REGISTRATION_FAILURE_EMAIL_TAKEN";
// export const REGISTRATION_FAILURE_PASSWORD_INVALID_CHARACTERS = "REGISTRATION_FAILURE_PASSWORD_INVALID_CHARACTERS";
