// >>> LOGIN
export const LOGIN_START = "LOGIN_START";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";
export const LOGIN_FAILURE_INVALID_EMAIL = "LOGIN_FAILURE_INVALID_EMAIL";
export const LOGIN_FAILURE_INVALID_PASSWORD = "LOGIN_FAILURE_INVALID_PASSWORD";
export const LOGIN_FAILURE_INVALID_PASSWORD_LENGTH = "LOGIN_FAILURE_INVALID_PASSWORD_LENGTH";

// >>> REGISTRATION
export const REGISTRATION_START = "REGISTRATION_START"
export const REGISTRATION_SUCCESS = "REGISTRATION_SUCCESS"
export const REGISTRATION_FAILURE = "REGISTRATION_FAILURE"
export const REGISTRATION_FAILURE_NO_ACCOUNT_TYPE = "REGISTRATION_FAILURE_NO_ACCOUNT_TYPE"
export const REGISTRATION_FAILURE_DUPLICATE_EMAIL = "REGISTRATION_FAILURE_DUPLICATE_EMAIL";
export const REGISTRATION_FAILURE_PASSWORD_INVALID_CHARACTERS = "REGISTRATION_FAILURE_PASSWORD_INVALID_CHARACTERS";

// >>> USER
export const RECEIVED_USER = "RECEIVED_USER";
export const CLEAR_USER = "CLEAR_USER"

export const UPDATING_USER_INFO_START = "UPDATING_USER_INFO_START";
export const UPDATING_USER_INFO_SUCCESS = "UPDATING_USER_INFO_SUCCESS";
export const UPDATING_USER_INFO_FAILURE = "UPDATING_USER_INFO_FAILURE";

export const DELETING_USER_START = "DELETING_USER_START";
export const DELETING_USER_SUCCESS = "DELETING_USER_SUCCESS";
export const DELETING_USER_FAILURE = "DELETING_USER_FAILURE";

// >>> BALANCE
export const GETTING_BALANCE_START = "GETTING_BALANCE_START";
export const GETTING_BALANCE_SUCCESS = "GETTING_BALANCE_SUCCESS";
export const GETTING_BALANCE_FAILURE = "GETTING_BALANCE_FAILURE";
export const CLEAR_BALANCE = "CLEAR_BALANCE";

// >>> SELECTING TIP
// Executes when a user selects a tip and clicks 'next', tip amount then gets stored in store
export const TIP_SET = "TIP_SET";
export const CLEAR_TIP = "CLEAR_TIP";

// >>> TIP RECEIVER
// Search takes place when entering it in the code-input, followed by selection and eventual deselection
export const TIP_RECEIVER_SEARCH_START = "TIP_RECEIVER_SEARCH_START";
export const TIP_RECEIVER_SEARCH_FAILURE = "TIP_RECEIVER_SEARCH_FAILURE"
export const TIP_RECEIVER_SEARCH_SUCCESS = "TIP_RECEIVER_SEARCH_SUCCESS"
export const TIP_RECEIVER_SET = "TIP_RECEIVER_SET";
export const CLEAR_TIP_RECEIVER = "CLEAR_TIP_RECEIVER";

// >>> TRANSACTIONS
export const SENDING_TRANSACTION_START = "SENDING_TRANSACTION_START";
export const SENDING_TRANSACTION_SUCCESS = "SENDING_TRANSACTION_SUCCESS";
export const SENDING_TRANSACTION_FAILURE = "SENDING_TRANSACTION_FAILURE";
export const CLEAR_CURRENT_TRANSACTION = "CLEAR_CURRENT_TRANSACTION";

export const FETCHING_TRANSACTIONS_START = "FETCHING_TRANSACTIONS_START";
export const FETCHING_TRANSACTIONS_SUCCESS = "FETCHING_TRANSACTIONS_SUCCESS";
export const FETCHING_TRANSACTIONS_FAILURE = "FETCHING_TRANSACTIONS_FAILURE";
export const CLEAR_TRANSACTIONS_LIST = "CLEAR_TRANSACTIONS_LIST";

// >>> DEPOSITING
export const SET_DEPOSIT_AMOUNT = "SET_DEPOSIT_AMOUNT";
export const CLEAR_DEPOSIT = "CLEAR_DEPOSIT";

export const DEPOSIT_START = "DEPOSIT_START";
export const DEPOSIT_SUCCESS = "DEPOSIT_SUCCESS";
export const DEPOSIT_FAILURE = "DEPOSIT_FAILURE";

// >>> WITHDRAWING
export const SET_WITHDRAWAL_AMOUNT = "SET_WITHDRAWAL_AMOUNT"
export const CLEAR_WITHDRAWAL = "CLEAR_WITHDRAWAL";

export const WITHDRAWAL_START = "WITHDRAWAL_START";
export const WITHDRAWAL_SUCCESS = "WITHDRAWAL_SUCCESS";
export const WITHDRAWAL_FAILURE = "WITHDRAWAL_FAILURE";

// >>> PAYMENT METHODS
export const FETCHING_PAYMENT_METHOD_START = "FETCHING_PAYMENT_METHOD_START";
export const FETCHING_PAYMENT_METHOD_SUCCESS = "FETCHING_PAYMENT_METHOD_SUCCESS";
export const FETCHING_PAYMENT_METHOD_FAILURE = "FETCHING_PAYMENT_METHOD_FAILURE";
export const CLEAR_PAYMENT_METHODS = "CLEAR_PAYMENT_METHODS";

export const ADDING_PAYMENT_METHOD_START = "ADDING_PAYMENT_METHOD_START";
export const ADDING_PAYMENT_METHOD_SUCCESS = "ADDING_PAYMENT_METHOD_SUCCESS";
export const ADDING_PAYMENT_METHOD_FAILURE = "ADDING_PAYMENT_METHOD_FAILURE";

export const REMOVING_PAYMENT_METHOD_START = "REMOVING_PAYMENT_METHOD_START";
export const REMOVING_PAYMENT_METHOD_SUCCESS = "REMOVING_PAYMENT_METHOD_SUCCESS";
export const REMOVING_PAYMENT_METHOD_FAILURE = "REMOVING_PAYMENT_METHOD_FAILURE";
