import React from 'react';

export const EnterCode = () => {
  const mockJSON = [
    {
      name: "Gabe",
      company: "Lambda School",
      code: "AG6373",
      imgUrl: "",
      imgAlt: "",
    },
    {
      name: "Dustin",
      company: "Chick-Fill-A",
      code: "CC1138",
      imgUrl: "",
      imgAlt: "",
    },
    {
      name: "Tom",
      company: "Apple",
      code: "WC4659",
      imgUrl: "",
      imgAlt: "",
    }
  ]


  return (
    <>
      <div className="inputContainer">
        <h2>Enter code for tip receiver</h2>
        {/* TO-DO: Research */}
        <input 
          type="text" 
          placeholder="AA1234" 
        />
      </div>

      <div className="usersContainer">
        {/* In the future, these will be generated by mapping over an array of user objects gathered from the back-end */}
        {/* TBR: Continuous search or after a .5s delay */}

        <div className="tipReceiver">
          <p>Select tip receiver below</p>
          
          {mockJSON.map((person, idx) => 
            <div key={idx}>
              <img src={person.imgUrl} alt={person.imgAlt} />
              <>
                <p>
                  <span>{person.name} </span>
                  from
                  <span> {person.company}</span>
                </p>
                <p>
                  <span>{person.code}</span>
                </p>
              </>
            </div>
          )}
        </div>
      </div>
    </>
  )
}

export default EnterCode;
