import React, { useState } from 'react';

import { connect } from 'react-redux'
import { bindActionCreators } from 'redux';


const EnterCode = (props) => {
  const [code, setCode] = useState('')

  const changeHandler = (e) => {
    let input = e.target.value

    // Allows for deleting first character.
    if (input.length === 0) {
      setCode(e.target.value)
    } 

    // Ensures first two characters will be uppercased letters
    else if (input.length <= 2) {
      input.slice(input.length-1).match(/[a-z]/i) ?
        setCode(e.target.value.toUpperCase())
          :
        setCode(code)
    } 
    // Ensures last four characters can only be numbers
    else if (input.length >= 3 && input.length <= 6 ) {
      let newDigit = e.target.value.slice(input.length-1, input.length);
      if (newDigit.match(/[0-9]/i)) {
        setCode(e.target.value)
      } else {
        setCode(code)
      }
    }
  }

  return (
    <>
      <div className="inputContainer">
        <h2>Enter code for tip receiver</h2>
        {/* TO-DO: Research 'staggered' inputs */}
        {/* TO-DO: Add ChangeHandler function that checks the input, compared to the length of the value */}
        {/*        for the first two, only allow letters (that are automatically capitalized) and number for the other four */}
        {/*        implement max-length as well */}
        <input 
          type="text" 
          placeholder="AA1234"
          onChange={(e) => changeHandler(e)}
          value={code}
        />
      </div>

      <div className="usersContainer">
        {/* In the future, these will be generated by mapping over an array of user objects gathered from the back-end */}
        {/* To Be Decided Upon: Continuous search or after a .5s delay */}

        <div className="tipReceiver">
          <p>Select tip receiver below</p>
          
          {props.receiverSearchResultsArray.map((person, idx) => 
            <div key={idx} onClick={() => props.history.push('/payment-method')}>
              <img src={person.imgUrl} alt={person.imgAlt} />
              <>
                <p>
                  <span>{person.name} </span>
                  from
                  <span> {person.company}</span>
                </p>
                <p>
                  <span>{person.code}</span>
                </p>
              </>
            </div>
          )}
        </div>
      </div>
    </>
  )
}

const mapStateToProps = (state) => {
  return {
    receiverSearchResultsArray: state.TipReceiverReducer.receiverSearchResultsArray
  }
}

const mapDispatchToProps = (dispatch) => {
  return bindActionCreators({
    
  }, dispatch)
}

export default connect(mapStateToProps, mapDispatchToProps)(EnterCode);
